CREATE OR REPLACE PROCEDURE insert_invoices()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
   insert into T_INVOICE(
	ORDER_ID,
	ORDER_DATE,
	INVOICE_DATE,
	TAX_AMOUNT,
	TOTAL_AMOUNT,
	DISCOUNT,
	FINAL_INVOICE_AMT,
	CUSTOMER_ID,
	CREATE_DATE,
	CREATE_USER) 
select T_SALES_ORDER_HEADER.ORDER_ID,
       T_SALES_ORDER_HEADER.ORDER_DATE,
       T_SALES_ORDER_HEADER.ORDER_DATE,
       0.09 * T_SALES_ORDER_HEADER.TOTAL_AMOUNT,
       T_SALES_ORDER_HEADER.TOTAL_AMOUNT,
       T_SALES_ORDER_HEADER.DISCOUNT,
       (T_SALES_ORDER_HEADER.TOTAL_AMOUNT + (0.09 * T_SALES_ORDER_HEADER.TOTAL_AMOUNT))- T_SALES_ORDER_HEADER.DISCOUNT,
       T_SALES_ORDER_HEADER.CUSTOMER_ID,
       T_SALES_ORDER_HEADER.CREATE_DATE,
       T_SALES_ORDER_HEADER.CREATE_USER
from T_SALES_ORDER_HEADER
join t_customer 
on T_SALES_ORDER_HEADER.CUSTOMER_ID = t_customer.CUSTOMER_ID
where T_SALES_ORDER_HEADER.order_date < current_date 
and t_customer.status = 'Active';
RETURN 'Insert operation completed successfully.';
END;