create or replace view ORDER_PROCESS.ORDER__XFRM.V_PROMOTION(
	PROMOTION_ID,
	CUSTOMER_CATEGORY,
	PROMOTION_TYPE,
	PROMOTION_VALUE,
	COMMENT
) as
select * FROM ORDER_PROCESS."ORDER _BASE".T_PROMOTION;