create or replace view ORDER_PROCESS.ORDER__XFRM.V_SALES_ORDER_DETAIL(
	ORDER_ID,
	ORDER_DATE,
	CUSTOMER_ID,
	ITEM_ID,
	QTY,
	TOTAL_AMOUNT,
	CREATE_DATE,
	CREATE_USER
) as
select * FROM ORDER_PROCESS."ORDER _BASE".T_SALES_ORDER_DETAIL;