CREATE OR REPLACE VIEW ORDER_PROCESS."ORDER__XFRM".V_PROMOTION (
    PROMOTION_ID,
    CUSTOMER_CATEGORY,
    PROMOTION_TYPE,
    PROMOTION_VALUE,
    COMMENT
) AS
SELECT 
    PROMOTION_ID, 
    CUSTOMER_CATEGORY, 
    PROMOTION_TYPE, 
    PROMOTION_VALUE, 
    COMMENT 
FROM 
    ORDER_PROCESS."ORDER_BASE".T_PROMOTION;
