create or replace view ORDER_PROCESS.ORDER__XFRM.V_PROMOTION(
	PROMOTION_ID,
	CUSTOMER_CATEGORY,
	PROMOTION_TYPE,
	PROMOTION_VALUE,
	COMMENT
) as
select PROMOTION_ID, CUSTOMER_CATEGORY,	PROMOTION_TYPE,	PROMOTION_VALUE, COMMENT FROM ORDER_PROCESS."ORDER_BASE".T_PROMOTION;