create or replace TABLE ORDER_PROCESS."ORDER _BASE".T_CUSTOMER (
	CUSTOMER_ID VARCHAR(10) NOT NULL,
	ADDRESS VARCHAR(50),
	PHONE_NO VARCHAR(10),
	CATEGORY VARCHAR(10),
	STATUS VARCHAR(10),
	TOTAL_ORDERS NUMBER(38,0),
	TOTAL_INVOICE_AMOUNT NUMBER(12,2),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR(10),
	LOYALTY_POINTS NUMBER(12,2),
	constraint PK_CUSTOMER_ID primary key (CUSTOMER_ID)
);

insert into t_customer
(CUSTOMER_ID, ADDRESS, PHONE_NO, CATEGORY, STATUS, TOTAL_ORDERS, TOTAL_INVOICE_AMOUNT, LOYALTY_POINTS, CREATE_DATE,	CREATE_USER)
values
('CUST-01', '2 Main StAnytown', '1234567890', 'Gold', 'Active', 3, 0, 0, DATE '2023-05-01', 'admin');