
create or replace TABLE ORDER_PROCESS."ORDER_BASE".T_SALES_ORDER_DETAIL (
	ORDER_ID VARCHAR(10) NOT NULL,
	ORDER_DATE DATE,
	CUSTOMER_ID VARCHAR(10),
	ITEM_ID VARCHAR(10),
	QTY NUMBER(38,0),
	TOTAL_AMOUNT NUMBER(12,2),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR(10),
    PRICE NUMBER(12,2)
);