create or replace TABLE ORDER_PROCESS."ORDER_BASE".T_PROMOTION (
	PROMOTION_ID VARCHAR(10) NOT NULL,
	CUSTOMER_CATEGORY VARCHAR(10),
	PROMOTION_TYPE VARCHAR(10),
	PROMOTION_VALUE NUMBER(10,2),
	COMMENT VARCHAR(20)
);