create or replace TABLE ORDER_PROCESS."ORDER_BASE".T_SALES_ORDER_HEADER (
	ORDER_ID VARCHAR(10) NOT NULL,
	ORDER_DATE DATE,
	STATUS VARCHAR(10),
	CUSTOMER_ID VARCHAR(10),
	ITEM_COUNT NUMBER(38,0),
	TOTAL_AMOUNT NUMBER(12,2),
	DISCOUNT NUMBER(10,2),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR(10),
    COUPON_CODE VARCHAR(10)
);